server:
  port: 80
spring:
  application:
    name: ericapp
  mandatory-file-encoding: UTF-8
  http:
    encoding:
      enabled: true
      charset: utf-8
  profiles:
    active: dev
  thymeleaf:
    mode: HTML5
    encoding: utf-8
    servlet:
      content-type: text/html
    cache: false
    #默认路径，可以不配
    prefix: classpath:/templates/
    suffix: .html
   #mvc:
     #view:
      #prefix: /WEB-INF/jsp/
      #suffix: .jsp
  kafka:
    producer:
      bootstrap-servers: 47.101.134.66:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      bootstrap-servers: 47.101.134.66:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
